## **Preparation :** Cleaning

#### _Nettoyage des donnÃ©es pour le Machine Learning_

ðŸŸ  `on work`

---

1. **VÃ©rifications**
    * Valeurs manquantes
    * Types de valeurs
    * Pertience des valeurs
    * Valeurs dupliquÃ©es

`---`

* [DataQuest :: Data Preparation for Machine Learning](https://www.dataquest.io/blog/machine-learning-preparing-data/)
* [Elite DataScience :: Pandas Content for Cleaning](https://elitedatascience.com/python-cheat-sheet)
* [Kaggle :: Handling Missing Values](https://www.kaggle.com/code/rtatman/data-cleaning-challenge-handling-missing-values/notebook)
* [Kaggle :: Preliminary Data Cleaning](https://www.kaggle.com/code/quannguyen135/preliminary-data-cleaning-with-python/notebook)

**Built-in**

**Librairies**

In [1]:
import numpy as np
import pandas as pd

**Notebook setup**

In [2]:
# Pandas
pd.options.display.max_rows = 30
pd.options.display.min_rows = 6

**NYC Squirrels dataset**

[NYC Squirrels from Open Data](https://opendata.cityofnewyork.us/)

In [3]:
squirrels_file_path = '../_datasets/nyc_squirrels_data.csv'
sqrl_data = pd.read_csv(squirrels_file_path)

sqrl_data

,X,Y,Unique Squirrel ID,Hectare,Shift,Date,Hectare Squirrel Number,Age,Primary Fur Color,Highlight Fur Color,...,Kuks,Quaas,Moans,Tail flags,Tail twitches,Approaches,Indifferent,Runs from,Other Interactions,Lat/Long
0,-73.956134,40.794082,37F-PM-1014-03,37F,PM,10142018,3,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,NaN,POINT (-73.9561344937861 40.7940823884086)
1,-73.957044,40.794851,37E-PM-1006-03,37E,PM,10062018,3,Adult,Gray,Cinnamon,...,False,False,False,False,False,False,False,True,me,POINT (-73.9570437717691 40.794850940803904)
2,-73.976831,40.766718,2E-AM-1010-03,02E,AM,10102018,3,Adult,Cinnamon,NaN,...,False,False,False,False,False,False,True,False,NaN,POINT (-73.9768311751004 40.76671780725581)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3020,-73.966587,40.783678,22D-PM-1012-07,22D,PM,10122018,7,Adult,Gray,"Black, Cinnamon, White",...,False,False,False,False,False,False,True,False,NaN,POINT (-73.9665871993517 40.7836775064883)
3021,-73.963994,40.789915,29B-PM-1010-02,29B,PM,10102018,2,NaN,Gray,"Cinnamon, White",...,False,False,False,False,False,False,True,False,NaN,POINT (-73.9639941227864 40.7899152327912)
3022,-73.975479,40.769640,5E-PM-1012-01,05E,PM,10122018,1,Adult,Cinnamon,"Gray, White",...,False,False,False,False,False,True,False,False,NaN,POINT (-73.9754794191553 40.7696404489025)

---
### **1.** VÃ©rifications

##### **1.1** - Valeurs manquanes

##### **1.2** - Types de valeurs

##### **1.3** - Pertinence des valeurs

##### **1.4** - Valeurs dupliquÃ©es